# Generated by Django 4.2.5 on 2023-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('surname', models.CharField(default='', max_length=60)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'msg',
            },
        ),
    ]
